// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/emergencias.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmergenciaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      int32                  `protobuf:"varint,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitude     int32                  `protobuf:"varint,4,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergenciaRequest) Reset() {
	*x = EmergenciaRequest{}
	mi := &file_proto_emergencias_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergenciaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergenciaRequest) ProtoMessage() {}

func (x *EmergenciaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencias_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergenciaRequest.ProtoReflect.Descriptor instead.
func (*EmergenciaRequest) Descriptor() ([]byte, []int) {
	return file_proto_emergencias_proto_rawDescGZIP(), []int{0}
}

func (x *EmergenciaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmergenciaRequest) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EmergenciaRequest) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *EmergenciaRequest) GetMagnitude() int32 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

type EmergenciaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergenciaResponse) Reset() {
	*x = EmergenciaResponse{}
	mi := &file_proto_emergencias_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergenciaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergenciaResponse) ProtoMessage() {}

func (x *EmergenciaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencias_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergenciaResponse.ProtoReflect.Descriptor instead.
func (*EmergenciaResponse) Descriptor() ([]byte, []int) {
	return file_proto_emergencias_proto_rawDescGZIP(), []int{1}
}

func (x *EmergenciaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EstadoEmergencia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // Ej: "En curso", "Extinguido"
	DronId        string                 `protobuf:"bytes,3,opt,name=dron_id,json=dronId,proto3" json:"dron_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstadoEmergencia) Reset() {
	*x = EstadoEmergencia{}
	mi := &file_proto_emergencias_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoEmergencia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoEmergencia) ProtoMessage() {}

func (x *EstadoEmergencia) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencias_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoEmergencia.ProtoReflect.Descriptor instead.
func (*EstadoEmergencia) Descriptor() ([]byte, []int) {
	return file_proto_emergencias_proto_rawDescGZIP(), []int{2}
}

func (x *EstadoEmergencia) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EstadoEmergencia) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EstadoEmergencia) GetDronId() string {
	if x != nil {
		return x.DronId
	}
	return ""
}

// Para asignación → drones
type AsignacionDronRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      int32                  `protobuf:"varint,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitude     int32                  `protobuf:"varint,4,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	DronId        string                 `protobuf:"bytes,5,opt,name=dron_id,json=dronId,proto3" json:"dron_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsignacionDronRequest) Reset() {
	*x = AsignacionDronRequest{}
	mi := &file_proto_emergencias_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsignacionDronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsignacionDronRequest) ProtoMessage() {}

func (x *AsignacionDronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencias_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsignacionDronRequest.ProtoReflect.Descriptor instead.
func (*AsignacionDronRequest) Descriptor() ([]byte, []int) {
	return file_proto_emergencias_proto_rawDescGZIP(), []int{3}
}

func (x *AsignacionDronRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AsignacionDronRequest) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AsignacionDronRequest) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AsignacionDronRequest) GetMagnitude() int32 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

func (x *AsignacionDronRequest) GetDronId() string {
	if x != nil {
		return x.DronId
	}
	return ""
}

var File_proto_emergencias_proto protoreflect.FileDescriptor

const file_proto_emergencias_proto_rawDesc = "" +
	"\n" +
	"\x17proto/emergencias.proto\x12\vemergencias\"\x7f\n" +
	"\x11EmergenciaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x05R\tlongitude\x12\x1c\n" +
	"\tmagnitude\x18\x04 \x01(\x05R\tmagnitude\".\n" +
	"\x12EmergenciaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"W\n" +
	"\x10EstadoEmergencia\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\adron_id\x18\x03 \x01(\tR\x06dronId\"\x9c\x01\n" +
	"\x15AsignacionDronRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x05R\tlongitude\x12\x1c\n" +
	"\tmagnitude\x18\x04 \x01(\x05R\tmagnitude\x12\x17\n" +
	"\adron_id\x18\x05 \x01(\tR\x06dronId2\xb8\x01\n" +
	"\n" +
	"Asignacion\x12S\n" +
	"\x10EnviarEmergencia\x12\x1e.emergencias.EmergenciaRequest\x1a\x1f.emergencias.EmergenciaResponse\x12U\n" +
	"\x12NotificarExtincion\x12\x1e.emergencias.EmergenciaRequest\x1a\x1f.emergencias.EmergenciaResponse2b\n" +
	"\x06Drones\x12X\n" +
	"\x11AsignarEmergencia\x12\".emergencias.AsignacionDronRequest\x1a\x1f.emergencias.EmergenciaResponse2_\n" +
	"\tMonitoreo\x12R\n" +
	"\x0fActualizaciones\x12\x1e.emergencias.EmergenciaRequest\x1a\x1d.emergencias.EstadoEmergencia0\x01B\x0fZ\rcliente/protob\x06proto3"

var (
	file_proto_emergencias_proto_rawDescOnce sync.Once
	file_proto_emergencias_proto_rawDescData []byte
)

func file_proto_emergencias_proto_rawDescGZIP() []byte {
	file_proto_emergencias_proto_rawDescOnce.Do(func() {
		file_proto_emergencias_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_emergencias_proto_rawDesc), len(file_proto_emergencias_proto_rawDesc)))
	})
	return file_proto_emergencias_proto_rawDescData
}

var file_proto_emergencias_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_emergencias_proto_goTypes = []any{
	(*EmergenciaRequest)(nil),     // 0: emergencias.EmergenciaRequest
	(*EmergenciaResponse)(nil),    // 1: emergencias.EmergenciaResponse
	(*EstadoEmergencia)(nil),      // 2: emergencias.EstadoEmergencia
	(*AsignacionDronRequest)(nil), // 3: emergencias.AsignacionDronRequest
}
var file_proto_emergencias_proto_depIdxs = []int32{
	0, // 0: emergencias.Asignacion.EnviarEmergencia:input_type -> emergencias.EmergenciaRequest
	0, // 1: emergencias.Asignacion.NotificarExtincion:input_type -> emergencias.EmergenciaRequest
	3, // 2: emergencias.Drones.AsignarEmergencia:input_type -> emergencias.AsignacionDronRequest
	0, // 3: emergencias.Monitoreo.Actualizaciones:input_type -> emergencias.EmergenciaRequest
	1, // 4: emergencias.Asignacion.EnviarEmergencia:output_type -> emergencias.EmergenciaResponse
	1, // 5: emergencias.Asignacion.NotificarExtincion:output_type -> emergencias.EmergenciaResponse
	1, // 6: emergencias.Drones.AsignarEmergencia:output_type -> emergencias.EmergenciaResponse
	2, // 7: emergencias.Monitoreo.Actualizaciones:output_type -> emergencias.EstadoEmergencia
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_emergencias_proto_init() }
func file_proto_emergencias_proto_init() {
	if File_proto_emergencias_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_emergencias_proto_rawDesc), len(file_proto_emergencias_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_emergencias_proto_goTypes,
		DependencyIndexes: file_proto_emergencias_proto_depIdxs,
		MessageInfos:      file_proto_emergencias_proto_msgTypes,
	}.Build()
	File_proto_emergencias_proto = out.File
	file_proto_emergencias_proto_goTypes = nil
	file_proto_emergencias_proto_depIdxs = nil
}
